#%RAML 1.0
title: Google Play Developer API
version: v1
baseUri: https://www.googleapis.com/androidpublisher/v1/applications/
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
  extras: https://raw.githubusercontent.com/apiregistry/typesExtras/master/typeExtras.raml
(commons.Links):
- title: Developer Documentation
  url: https://developers.google.com/android-publisher
  role: documentation
(commons.Icons):
- url: https://www.google.com/images/icons/product/android-32.png
  name: x32
- url: https://www.google.com/images/icons/product/android-16.png
  name: x16
(commons.Id): androidpublisher:v1
securitySchemes:
  oath2:
    type: OAuth 2.0
    description: Google Oath2.0 authorization. Detailed documentation can be found at https://developers.google.com/identity/protocols/OAuth2
    settings:
      authorizationGrants:
      - authorization_code
      - implicit
      authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      scopes:
      - https://www.googleapis.com/auth/androidpublisher
    (commons.OathScopeDescriptions):
    - View and manage your Google Play Developer account
traits:
  hasParameters:
    queryParameters:
      quotaUser?:
        type: string
        description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.
      prettyPrint?:
        type: boolean
        default: true
        description: Returns response with indentations and line breaks.
      userIp?:
        type: string
        description: IP address of the site where the request originates. Use this if you want to enforce per-user limits.
      fields?:
        type: string
        description: Selector specifying which fields to include in a partial response.
securedBy:
  oath2: 
types:
  SubscriptionPurchase:
    type: object
    properties:
      validUntilTimestampMsec?:
        type: integer
        format: int64
        description: Time at which the subscription will expire, in milliseconds since the Epoch.
      initiationTimestampMsec?:
        type: integer
        format: int64
        description: Time at which the subscription was granted, in milliseconds since the Epoch.
      kind?:
        type: string
        default: androidpublisher#subscriptionPurchase
        description: This kind represents a subscriptionPurchase object in the androidpublisher service.
      autoRenewing?:
        type: boolean
        description: Whether the subscription will automatically be renewed when it reaches its current expiry time.
    description: A SubscriptionPurchase resource indicates the status of a user's subscription purchase.
/{packageName}:
  uriParameters:
    packageName:
      type: string
      description: The package name of the application for which this subscription was purchased (for example, 'com.some.thing').
  /subscriptions:
    /{subscriptionId}:
      uriParameters:
        subscriptionId:
          type: string
          description: The purchased subscription ID (for example, 'monthly001').
      /purchases:
        /{token}:
          uriParameters:
            token:
              type: string
              description: The token provided to the user's device when the subscription was purchased.
          /cancel:
            post:
              securedBy:
                oath2:
                  scopes:
                  - https://www.googleapis.com/auth/androidpublisher
              description: Cancels a user's subscription purchase. The subscription remains valid until its expiration time.
              displayName: Cancel
              is:
              - hasParameters
              (commons.Id): androidpublisher.purchases.cancel
              (commons.LogicalStructure):
              - Purchases
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/androidpublisher
            description: Checks whether a user's subscription purchase is valid and returns its expiry time.
            displayName: Get
            is:
            - hasParameters
            responses:
              200:
                body:
                  application/json: SubscriptionPurchase
            (commons.Id): androidpublisher.purchases.get
            (commons.LogicalStructure):
            - Purchases
