#%RAML 1.0
title: Google Cloud DNS API
version: v2beta1
baseUri: https://www.googleapis.com/dns/v2beta1/projects/
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
(commons.Links):
- title: Developer Documentation
  url: https://developers.google.com/cloud-dns
  role: documentation
(commons.Icons):
- url: http://www.google.com/images/icons/product/search-32.gif
  name: x32
- url: http://www.google.com/images/icons/product/search-16.gif
  name: x16
(commons.Id): dns:v2beta1
securitySchemes:
  oath2:
    type: OAuth 2.0
    description: Google Oath2.0 authorization. Detailed documentation can be found at https://developers.google.com/identity/protocols/OAuth2
    settings:
      authorizationGrants:
      - authorization_code
      - implicit
      authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      scopes:
      - https://www.googleapis.com/auth/ndev.clouddns.readwrite
      - https://www.googleapis.com/auth/ndev.clouddns.readonly
      - https://www.googleapis.com/auth/cloud-platform.read-only
      - https://www.googleapis.com/auth/cloud-platform
traits:
  hasParameters:
    queryParameters:
      quotaUser?:
        type: string
        description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.
      prettyPrint?:
        type: boolean
        default: true
        description: Returns response with indentations and line breaks.
      userIp?:
        type: string
        description: IP address of the site where the request originates. Use this if you want to enforce per-user limits.
      fields?:
        type: string
        description: Selector specifying which fields to include in a partial response.
securedBy:
  oath2: 
types:
  Change:
    type: object
    properties:
      additions?:
        type: array
        description: Which ResourceRecordSets to add?
        items: ResourceRecordSet
      deletions?:
        type: array
        description: Which ResourceRecordSets to remove? Must match existing data exactly.
        items: ResourceRecordSet
      kind?:
        type: string
        default: dns#change
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#change".'
      isServing?:
        type: boolean
        description: If the DNS queries for the zone will be served.
      startTime?:
        type: string
        description: The time that this operation was started by the server (output only). This is in RFC3339 text format.
      id?:
        type: string
        description: Unique identifier for the resource; defined by the server (output only).
      status?:
        type: string
        description: Status of the operation (output only).
        enum:
        - DONE
        - PENDING
    description: An atomic update to a collection of ResourceRecordSets.
  ChangesListResponse:
    type: object
    properties:
      kind?:
        type: string
        default: dns#changesListResponse
        description: Type of resource.
      nextPageToken?:
        type: string
        description: |-
          The presence of this field indicates that there exist more results following your last page of results in pagination order. To fetch them, make another list request using this value as your pagination token.

          In this way you can retrieve the complete contents of even very large collections one page at a time. However, if the contents of the collection change between the first and last paginated list request, the set of all elements returned will be an inconsistent view of the collection. There is no way to retrieve a "snapshot" of collections larger than the maximum page size.
      changes?:
        type: array
        description: The requested changes.
        items: Change
      header?: ResponseHeader
    description: The response to a request to enumerate Changes to a ResourceRecordSets collection.
  DnsKey:
    type: object
    properties:
      keyLength?:
        type: integer
        format: int32
        description: Length of the key in bits. Specified at creation time then immutable.
      creationTime?:
        type: string
        description: The time that this resource was created in the control plane. This is in RFC3339 text format. Output only.
      keyTag?:
        type: integer
        format: int32
        description: The key tag is a non-cryptographic hash of the a DNSKEY resource record associated with this DnsKey. The key tag can be used to identify a DNSKEY more quickly (but it is not a unique identifier). In particular, the key tag is used in a parent zone's DS record to point at the DNSKEY in this child ManagedZone. The key tag is a number in the range [0, 65535] and the algorithm to calculate it is specified in RFC4034 Appendix B. Output only.
      kind?:
        type: string
        default: dns#dnsKey
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#dnsKey".'
      digests?:
        type: array
        description: Cryptographic hashes of the DNSKEY resource record associated with this DnsKey. These digests are needed to construct a DS record that points at this DNS key. Output only.
        items: DnsKeyDigest
      description?:
        type: string
        description: A mutable string of at most 1024 characters associated with this resource for the user's convenience. Has no effect on the resource's function.
      id?:
        type: string
        description: Unique identifier for the resource; defined by the server (output only).
      publicKey?:
        type: string
        description: Base64 encoded public half of this key. Output only.
      isActive?:
        type: boolean
        description: Active keys will be used to sign subsequent changes to the ManagedZone. Inactive keys will still be present as DNSKEY Resource Records for the use of resolvers validating existing signatures.
      type?:
        type: string
        description: One of "KEY_SIGNING" or "ZONE_SIGNING". Keys of type KEY_SIGNING have the Secure Entry Point flag set and, when active, will be used to sign only resource record sets of type DNSKEY. Otherwise, the Secure Entry Point flag will be cleared and this key will be used to sign only resource record sets of other types. Immutable after creation time.
        enum:
        - KEY_SIGNING
        - ZONE_SIGNING
      algorithm?:
        type: string
        description: String mnemonic specifying the DNSSEC algorithm of this key. Immutable after creation time.
        enum:
        - ECDSAP256SHA256
        - ECDSAP384SHA384
        - RSASHA1
        - RSASHA256
        - RSASHA512
    description: A DNSSEC key pair.
  DnsKeyDigest:
    type: object
    properties:
      digest?:
        type: string
        description: The base-16 encoded bytes of this digest. Suitable for use in a DS resource record.
      type?:
        type: string
        description: Specifies the algorithm used to calculate this digest.
        enum:
        - SHA1
        - SHA256
        - SHA384
  DnsKeySpec:
    type: object
    properties:
      keyLength?:
        type: integer
        format: int32
        description: Length of the keys in bits.
      kind?:
        type: string
        default: dns#dnsKeySpec
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#dnsKeySpec".'
      keyType?:
        type: string
        description: One of "KEY_SIGNING" or "ZONE_SIGNING". Keys of type KEY_SIGNING have the Secure Entry Point flag set and, when active, will be used to sign only resource record sets of type DNSKEY. Otherwise, the Secure Entry Point flag will be cleared and this key will be used to sign only resource record sets of other types.
        enum:
        - KEY_SIGNING
        - ZONE_SIGNING
      algorithm?:
        type: string
        description: String mnemonic specifying the DNSSEC algorithm of this key.
        enum:
        - ECDSAP256SHA256
        - ECDSAP384SHA384
        - RSASHA1
        - RSASHA256
        - RSASHA512
    description: Parameters for DnsKey key generation. Used for generating initial keys for a new ManagedZone and as default when adding a new DnsKey.
  DnsKeysListResponse:
    type: object
    properties:
      dnsKeys?:
        type: array
        description: The requested resources.
        items: DnsKey
      kind?:
        type: string
        default: dns#dnsKeysListResponse
        description: Type of resource.
      nextPageToken?:
        type: string
        description: |-
          The presence of this field indicates that there exist more results following your last page of results in pagination order. To fetch them, make another list request using this value as your pagination token.

          In this way you can retrieve the complete contents of even very large collections one page at a time. However, if the contents of the collection change between the first and last paginated list request, the set of all elements returned will be an inconsistent view of the collection. There is no way to retrieve a "snapshot" of collections larger than the maximum page size.
      header?: ResponseHeader
    description: The response to a request to enumerate DnsKeys in a ManagedZone.
  ManagedZone:
    type: object
    properties:
      dnssecConfig?: ManagedZoneDnsSecConfig
      creationTime?:
        type: string
        description: The time that this resource was created on the server. This is in RFC3339 text format. Output only.
      kind?:
        type: string
        default: dns#managedZone
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#managedZone".'
      nameServerSet?:
        type: string
        description: Optionally specifies the NameServerSet for this ManagedZone. A NameServerSet is a set of DNS name servers that all host the same ManagedZones. Most users will leave this field unset.
      name?:
        type: string
        description: User assigned name for this resource. Must be unique within the project. The name must be 1-63 characters long, must begin with a letter, end with a letter or digit, and only contain lowercase letters, digits or dashes.
      description?:
        type: string
        description: A mutable string of at most 1024 characters associated with this resource for the user's convenience. Has no effect on the managed zone's function.
      dnsName?:
        type: string
        description: The DNS name of this managed zone, for instance "example.com.".
      id?:
        type: integer
        format: int64
        description: Unique identifier for the resource; defined by the server (output only)
      nameServers?:
        type: array
        description: Delegate your managed_zone to these virtual name servers; defined by the server (output only)
        items:
          type: string
    description: A zone is a subtree of the DNS namespace under one administrative responsibility. A ManagedZone is a resource that represents a DNS zone hosted by the Cloud DNS service.
  ManagedZoneDnsSecConfig:
    type: object
    properties:
      defaultKeySpecs?:
        type: array
        description: Specifies parameters that will be used for generating initial DnsKeys for this ManagedZone. Output only while state is not OFF.
        items: DnsKeySpec
      kind?:
        type: string
        default: dns#managedZoneDnsSecConfig
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#managedZoneDnsSecConfig".'
      state?:
        type: string
        description: Specifies whether DNSSEC is enabled, and what mode it is in.
        enum:
        - 'OFF'
        - 'ON'
        - TRANSFER
      nonExistence?:
        type: string
        description: Specifies the mechanism used to provide authenticated denial-of-existence responses. Output only while state is not OFF.
        enum:
        - NSEC
        - NSEC3
  ManagedZoneOperationsListResponse:
    type: object
    properties:
      operations?:
        type: array
        description: The operation resources.
        items: Operation
      kind?:
        type: string
        default: dns#managedZoneOperationsListResponse
        description: Type of resource.
      nextPageToken?:
        type: string
        description: |-
          The presence of this field indicates that there exist more results following your last page of results in pagination order. To fetch them, make another list request using this value as your page token.

          In this way you can retrieve the complete contents of even very large collections one page at a time. However, if the contents of the collection change between the first and last paginated list request, the set of all elements returned will be an inconsistent view of the collection. There is no way to retrieve a consistent snapshot of a collection larger than the maximum page size.
      header?: ResponseHeader
  ManagedZonesDeleteResponse:
    type: object
    properties:
      header?: ResponseHeader
  ManagedZonesListResponse:
    type: object
    properties:
      kind?:
        type: string
        default: dns#managedZonesListResponse
        description: Type of resource.
      nextPageToken?:
        type: string
        description: |-
          The presence of this field indicates that there exist more results following your last page of results in pagination order. To fetch them, make another list request using this value as your page token.

          In this way you can retrieve the complete contents of even very large collections one page at a time. However, if the contents of the collection change between the first and last paginated list request, the set of all elements returned will be an inconsistent view of the collection. There is no way to retrieve a consistent snapshot of a collection larger than the maximum page size.
      header?: ResponseHeader
      managedZones?:
        type: array
        description: The managed zone resources.
        items: ManagedZone
  Operation:
    type: object
    properties:
      zoneContext?: OperationManagedZoneContext
      kind?:
        type: string
        default: dns#operation
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#operation".'
      dnsKeyContext?: OperationDnsKeyContext
      startTime?:
        type: string
        description: The time that this operation was started by the server. This is in RFC3339 text format (output only).
      id?:
        type: string
        description: Unique identifier for the resource. This is the client_operation_id if the client specified it when the mutation was initiated, otherwise, it is generated by the server. The name must be 1-63 characters long and match the regular expression [-a-z0-9]? (output only)
      type?:
        type: string
        description: Type of the operation. Operations include insert, update, and delete (output only).
      user?:
        type: string
        description: 'User who requested the operation, for example: user@example.com.
          cloud-dns-system for operations automatically done by the system. (output
          only)'
      status?:
        type: string
        description: 'Status of the operation. Can be one of the following: "PENDING"
          or "DONE" (output only).'
        enum:
        - DONE
        - PENDING
    description: 'An operation represents a successful mutation performed on a Cloud
      DNS resource. Operations provide: - An audit log of server resource mutations.
      - A way to recover/retry API calls in the case where the response is never received
      by the caller. Use the caller specified client_operation_id.'
  OperationDnsKeyContext:
    type: object
    properties:
      newValue?: DnsKey
      oldValue?: DnsKey
  OperationManagedZoneContext:
    type: object
    properties:
      newValue?: ManagedZone
      oldValue?: ManagedZone
  Project:
    type: object
    properties:
      number?:
        type: integer
        format: int64
        description: Unique numeric identifier for the resource; defined by the server (output only).
      kind?:
        type: string
        default: dns#project
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#project".'
      quota?: Quota
      id?:
        type: string
        description: User assigned unique identifier for the resource (output only).
    description: A project resource. The project is a top level container for resources including Cloud DNS ManagedZones. Projects can be created only in the APIs console.
  Quota:
    type: object
    properties:
      rrsetAdditionsPerChange?:
        type: integer
        format: int32
        description: Maximum allowed number of ResourceRecordSets to add per ChangesCreateRequest.
      rrsetDeletionsPerChange?:
        type: integer
        format: int32
        description: Maximum allowed number of ResourceRecordSets to delete per ChangesCreateRequest.
      whitelistedKeySpecs?:
        type: array
        description: DNSSEC algorithm and key length types that can be used for DnsKeys.
        items: DnsKeySpec
      kind?:
        type: string
        default: dns#quota
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#quota".'
      dnsKeysPerManagedZone?:
        type: integer
        format: int32
        description: Maximum allowed number of DnsKeys per ManagedZone.
      resourceRecordsPerRrset?:
        type: integer
        format: int32
        description: Maximum allowed number of ResourceRecords per ResourceRecordSet.
      totalRrdataSizePerChange?:
        type: integer
        format: int32
        description: Maximum allowed size for total rrdata in one ChangesCreateRequest in bytes.
      managedZones?:
        type: integer
        format: int32
        description: Maximum allowed number of managed zones in the project.
      rrsetsPerManagedZone?:
        type: integer
        format: int32
        description: Maximum allowed number of ResourceRecordSets per zone in the project.
    description: Limits associated with a Project.
  ResourceRecordSet:
    type: object
    properties:
      rrdatas?:
        type: array
        description: As defined in RFC 1035 (section 5) and RFC 1034 (section 3.6.1).
        items:
          type: string
      kind?:
        type: string
        default: dns#resourceRecordSet
        description: 'Identifies what kind of resource this is. Value: the fixed string
          "dns#resourceRecordSet".'
      signatureRrdatas?:
        type: array
        description: As defined in RFC 4034 (section 3.2).
        items:
          type: string
      name?:
        type: string
        description: For example, www.example.com.
      type?:
        type: string
        description: The identifier of a supported record type, for example, A, AAAA, MX, TXT, and so on.
      ttl?:
        type: integer
        format: int32
        description: Number of seconds that this ResourceRecordSet can be cached by resolvers.
    description: A unit of data that will be returned by the DNS servers.
  ResourceRecordSetsListResponse:
    type: object
    properties:
      rrsets?:
        type: array
        description: The resource record set resources.
        items: ResourceRecordSet
      kind?:
        type: string
        default: dns#resourceRecordSetsListResponse
        description: Type of resource.
      nextPageToken?:
        type: string
        description: |-
          The presence of this field indicates that there exist more results following your last page of results in pagination order. To fetch them, make another list request using this value as your pagination token.

          In this way you can retrieve the complete contents of even very large collections one page at a time. However, if the contents of the collection change between the first and last paginated list request, the set of all elements returned will be an inconsistent view of the collection. There is no way to retrieve a consistent snapshot of a collection larger than the maximum page size.
      header?: ResponseHeader
  ResponseHeader:
    type: object
    properties:
      operationId?:
        type: string
        description: For mutating operation requests that completed successfully. This is the client_operation_id if the client specified it, otherwise it is generated by the server (output only).
    description: Elements common to every response.
/{project}:
  uriParameters:
    project:
      type: string
      description: Identifies the project addressed by this request.
  /managedZones:
    /{managedZone}:
      uriParameters:
        managedZone:
          type: string
          description: Identifies the managed zone addressed by this request.
      /operations:
        /{operation}:
          uriParameters:
            operation:
              type: string
              description: Identifies the operation addressed by this request.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/cloud-platform
                - https://www.googleapis.com/auth/cloud-platform.read-only
                - https://www.googleapis.com/auth/ndev.clouddns.readonly
                - https://www.googleapis.com/auth/ndev.clouddns.readwrite
            description: Fetch the representation of an existing Operation.
            displayName: Get ManagedZoneOperations
            is:
            - hasParameters
            queryParameters:
              clientOperationId?:
                type: string
                description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
            responses:
              200:
                body:
                  application/json: Operation
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/cloud-platform.read-only
              - https://www.googleapis.com/auth/ndev.clouddns.readonly
              - https://www.googleapis.com/auth/ndev.clouddns.readwrite
          description: Enumerate Operations for the given ManagedZone.
          displayName: List ManagedZoneOperations
          is:
          - hasParameters
          queryParameters:
            maxResults?:
              type: integer
              format: int32
              description: Optional. Maximum number of results to be returned. If unspecified, the server will decide how many results to return.
            sortBy?:
              type: string
              default: START_TIME
              description: Sorting criterion. The only supported values are START_TIME and ID.
              enum:
              - ID
              - START_TIME
            pageToken?:
              type: string
              description: Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
          responses:
            200:
              body:
                application/json: ManagedZoneOperationsListResponse
      /dnsKeys:
        /{dnsKeyId}:
          uriParameters:
            dnsKeyId:
              type: string
              description: The identifier of the requested DnsKey.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/cloud-platform
                - https://www.googleapis.com/auth/cloud-platform.read-only
                - https://www.googleapis.com/auth/ndev.clouddns.readonly
                - https://www.googleapis.com/auth/ndev.clouddns.readwrite
            description: Fetch the representation of an existing DnsKey.
            displayName: Get Dnskeys
            is:
            - hasParameters
            queryParameters:
              digestType?:
                type: string
                description: An optional comma-separated list of digest types to compute and display for key signing keys. If omitted, the recommended digest type will be computed and displayed.
              clientOperationId?:
                type: string
                description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
            responses:
              200:
                body:
                  application/json: DnsKey
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/cloud-platform.read-only
              - https://www.googleapis.com/auth/ndev.clouddns.readonly
              - https://www.googleapis.com/auth/ndev.clouddns.readwrite
          description: Enumerate DnsKeys to a ResourceRecordSet collection.
          displayName: List Dnskeys
          is:
          - hasParameters
          queryParameters:
            digestType?:
              type: string
              description: An optional comma-separated list of digest types to compute and display for key signing keys. If omitted, the recommended digest type will be computed and displayed.
            maxResults?:
              type: integer
              format: int32
              description: Optional. Maximum number of results to be returned. If unspecified, the server will decide how many results to return.
            pageToken?:
              type: string
              description: Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
          responses:
            200:
              body:
                application/json: DnsKeysListResponse
      /rrsets:
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/cloud-platform.read-only
              - https://www.googleapis.com/auth/ndev.clouddns.readonly
              - https://www.googleapis.com/auth/ndev.clouddns.readwrite
          description: Enumerate ResourceRecordSets that have been created but not yet deleted.
          displayName: List ResourceRecordSets
          is:
          - hasParameters
          queryParameters:
            maxResults?:
              type: integer
              format: int32
              description: Optional. Maximum number of results to be returned. If unspecified, the server will decide how many results to return.
            name?:
              type: string
              description: Restricts the list to return only records with this fully qualified domain name.
            pageToken?:
              type: string
              description: Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
            type?:
              type: string
              description: Restricts the list to return only records of this type. If present, the "name" parameter must also be present.
          responses:
            200:
              body:
                application/json: ResourceRecordSetsListResponse
      /changes:
        /{changeId}:
          uriParameters:
            changeId:
              type: string
              description: The identifier of the requested change, from a previous ResourceRecordSetsChangeResponse.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/cloud-platform
                - https://www.googleapis.com/auth/cloud-platform.read-only
                - https://www.googleapis.com/auth/ndev.clouddns.readonly
                - https://www.googleapis.com/auth/ndev.clouddns.readwrite
            description: Fetch the representation of an existing Change.
            displayName: Get Changes
            is:
            - hasParameters
            queryParameters:
              clientOperationId?:
                type: string
                description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
            responses:
              200:
                body:
                  application/json: Change
        post:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/ndev.clouddns.readwrite
          description: Atomically update the ResourceRecordSet collection.
          displayName: Create Changes
          is:
          - hasParameters
          queryParameters:
            clientOperationId?:
              type: string
              description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
          body:
            application/json: Change
          responses:
            200:
              body:
                application/json: Change
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/cloud-platform
              - https://www.googleapis.com/auth/cloud-platform.read-only
              - https://www.googleapis.com/auth/ndev.clouddns.readonly
              - https://www.googleapis.com/auth/ndev.clouddns.readwrite
          description: Enumerate Changes to a ResourceRecordSet collection.
          displayName: List Changes
          is:
          - hasParameters
          queryParameters:
            maxResults?:
              type: integer
              format: int32
              description: Optional. Maximum number of results to be returned. If unspecified, the server will decide how many results to return.
            sortOrder?:
              type: string
              description: 'Sorting order direction: ''ascending'' or ''descending''.'
            sortBy?:
              type: string
              default: CHANGE_SEQUENCE
              description: Sorting criterion. The only supported value is change sequence.
              enum:
              - CHANGE_SEQUENCE
            pageToken?:
              type: string
              description: Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
          responses:
            200:
              body:
                application/json: ChangesListResponse
      patch:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/ndev.clouddns.readwrite
        description: Update an existing ManagedZone. This method supports patch semantics.
        displayName: Patch ManagedZones
        is:
        - hasParameters
        queryParameters:
          clientOperationId?:
            type: string
            description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
        body:
          application/json: ManagedZone
        responses:
          200:
            body:
              application/json: Operation
      get:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/cloud-platform.read-only
            - https://www.googleapis.com/auth/ndev.clouddns.readonly
            - https://www.googleapis.com/auth/ndev.clouddns.readwrite
        description: Fetch the representation of an existing ManagedZone.
        displayName: Get ManagedZones
        is:
        - hasParameters
        queryParameters:
          clientOperationId?:
            type: string
            description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
        responses:
          200:
            body:
              application/json: ManagedZone
      put:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/ndev.clouddns.readwrite
        description: Update an existing ManagedZone.
        displayName: Update ManagedZones
        is:
        - hasParameters
        queryParameters:
          clientOperationId?:
            type: string
            description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
        body:
          application/json: ManagedZone
        responses:
          200:
            body:
              application/json: Operation
      delete:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/cloud-platform
            - https://www.googleapis.com/auth/ndev.clouddns.readwrite
        description: Delete a previously created ManagedZone.
        displayName: Delete ManagedZones
        is:
        - hasParameters
        queryParameters:
          clientOperationId?:
            type: string
            description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
        responses:
          200:
            body:
              application/json: ManagedZonesDeleteResponse
    post:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/cloud-platform
          - https://www.googleapis.com/auth/ndev.clouddns.readwrite
      description: Create a new ManagedZone.
      displayName: Create ManagedZones
      is:
      - hasParameters
      queryParameters:
        clientOperationId?:
          type: string
          description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
      body:
        application/json: ManagedZone
      responses:
        200:
          body:
            application/json: ManagedZone
    get:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/cloud-platform
          - https://www.googleapis.com/auth/cloud-platform.read-only
          - https://www.googleapis.com/auth/ndev.clouddns.readonly
          - https://www.googleapis.com/auth/ndev.clouddns.readwrite
      description: Enumerate ManagedZones that have been created but not yet deleted.
      displayName: List ManagedZones
      is:
      - hasParameters
      queryParameters:
        maxResults?:
          type: integer
          format: int32
          description: Optional. Maximum number of results to be returned. If unspecified, the server will decide how many results to return.
        dnsName?:
          type: string
          description: Restricts the list to return only zones with this domain name.
        pageToken?:
          type: string
          description: Optional. A tag returned by a previous list request that was truncated. Use this parameter to continue a previous list request.
      responses:
        200:
          body:
            application/json: ManagedZonesListResponse
  get:
    securedBy:
      oath2:
        scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/cloud-platform.read-only
        - https://www.googleapis.com/auth/ndev.clouddns.readonly
        - https://www.googleapis.com/auth/ndev.clouddns.readwrite
    description: Fetch the representation of an existing Project.
    displayName: Get Projects
    is:
    - hasParameters
    queryParameters:
      clientOperationId?:
        type: string
        description: For mutating operation requests only. An optional identifier specified by the client. Must be unique for operation resources in the Operations collection.
    responses:
      200:
        body:
          application/json: Project
