#%RAML 1.0
title: Google Play Game Services Publishing API
version: v1configuration
baseUri: https://www.googleapis.com/games/v1configuration/
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
(commons.Links):
- title: Developer Documentation
  url: https://developers.google.com/games/services
  role: documentation
(commons.Icons):
- url: http://www.google.com/images/icons/product/search-32.gif
  name: x32
- url: http://www.google.com/images/icons/product/search-16.gif
  name: x16
(commons.Id): gamesConfiguration:v1configuration
securitySchemes:
  oath2:
    type: OAuth 2.0
    description: Google Oath2.0 authorization. Detailed documentation can be found at https://developers.google.com/identity/protocols/OAuth2
    settings:
      authorizationGrants:
      - authorization_code
      - implicit
      authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      scopes:
      - https://www.googleapis.com/auth/androidpublisher
traits:
  hasParameters:
    queryParameters:
      quotaUser?:
        type: string
        description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.
      prettyPrint?:
        type: boolean
        default: true
        description: Returns response with indentations and line breaks.
      userIp?:
        type: string
        description: IP address of the site where the request originates. Use this if you want to enforce per-user limits.
      fields?:
        type: string
        description: Selector specifying which fields to include in a partial response.
securedBy:
  oath2: 
types:
  AchievementConfiguration:
    type: object
    properties:
      achievementType?:
        type: string
        description: "The type of the achievement.\nPossible values are:  \n- \"STANDARD\"\
          \ - Achievement is either locked or unlocked. \n- \"INCREMENTAL\" - Achievement\
          \ is incremental."
      stepsToUnlock?:
        type: integer
        format: int32
        description: Steps to unlock. Only applicable to incremental achievements.
      initialState?:
        type: string
        description: "The initial state of the achievement.\nPossible values are:\
          \  \n- \"HIDDEN\" - Achievement is hidden. \n- \"REVEALED\" - Achievement\
          \ is revealed. \n- \"UNLOCKED\" - Achievement is unlocked."
      kind?:
        type: string
        default: gamesConfiguration#achievementConfiguration
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#achievementConfiguration.
      draft?: AchievementConfigurationDetail
      id?:
        type: string
        description: The ID of the achievement.
      published?: AchievementConfigurationDetail
      token?:
        type: string
        description: The token for this resource.
    description: This is a JSON template for an achievement configuration resource.
  AchievementConfigurationDetail:
    type: object
    properties:
      pointValue?:
        type: integer
        format: int32
        description: Point value for the achievement.
      kind?:
        type: string
        default: gamesConfiguration#achievementConfigurationDetail
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#achievementConfigurationDetail.
      sortRank?:
        type: integer
        format: int32
        description: The sort rank of this achievement. Writes to this field are ignored.
      name?: LocalizedStringBundle
      description?: LocalizedStringBundle
      iconUrl?:
        type: string
        description: The icon url of this achievement. Writes to this field are ignored.
    description: This is a JSON template for an achievement configuration detail.
  AchievementConfigurationListResponse:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#achievementConfigurationListResponse
        description: Uniquely identifies the type of this resource. Value is always the fixed string games#achievementConfigurationListResponse.
      nextPageToken?:
        type: string
        description: The pagination token for the next page of results.
      items?:
        type: array
        description: The achievement configurations.
        items: AchievementConfiguration
    description: This is a JSON template for a ListConfigurations response.
  GamesNumberAffixConfiguration:
    type: object
    properties:
      zero?: LocalizedStringBundle
      other?: LocalizedStringBundle
      one?: LocalizedStringBundle
      few?: LocalizedStringBundle
      many?: LocalizedStringBundle
      two?: LocalizedStringBundle
    description: This is a JSON template for a number affix resource.
  GamesNumberFormatConfiguration:
    type: object
    properties:
      numberFormatType?:
        type: string
        description: "The formatting for the number.\nPossible values are:  \n- \"\
          NUMERIC\" - Numbers are formatted to have no digits or a fixed number of\
          \ digits after the decimal point according to locale. An optional custom\
          \ unit can be added.\n- \"TIME_DURATION\" - Numbers are formatted to hours,\
          \ minutes and seconds.\n- \"CURRENCY\" - Numbers are formatted to currency\
          \ according to locale."
      numDecimalPlaces?:
        type: integer
        format: int32
        description: The number of decimal places for number. Only used for NUMERIC format type.
      suffix?: GamesNumberAffixConfiguration
      currencyCode?:
        type: string
        description: The curreny code string. Only used for CURRENCY format type.
    description: This is a JSON template for a number format resource.
  ImageConfiguration:
    type: object
    properties:
      resourceId?:
        type: string
        description: The resource ID of resource which the image belongs to.
      kind?:
        type: string
        default: gamesConfiguration#imageConfiguration
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#imageConfiguration.
      imageType?:
        type: string
        description: The image type for the image.
      url?:
        type: string
        description: The url for this image.
    description: This is a JSON template for an image configuration resource.
  LeaderboardConfiguration:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#leaderboardConfiguration
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#leaderboardConfiguration.
      draft?: LeaderboardConfigurationDetail
      scoreOrder?:
        type: string
        description: "The type of the leaderboard.\nPossible values are:  \n- \"LARGER_IS_BETTER\"\
          \ - Larger scores posted are ranked higher. \n- \"SMALLER_IS_BETTER\" -\
          \ Smaller scores posted are ranked higher."
      id?:
        type: string
        description: The ID of the leaderboard.
      published?: LeaderboardConfigurationDetail
      scoreMax?:
        type: integer
        format: int64
        description: Maximum score that can be posted to this leaderboard.
      scoreMin?:
        type: integer
        format: int64
        description: Minimum score that can be posted to this leaderboard.
      token?:
        type: string
        description: The token for this resource.
    description: This is a JSON template for an leaderboard configuration resource.
  LeaderboardConfigurationDetail:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#leaderboardConfigurationDetail
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#leaderboardConfigurationDetail.
      scoreFormat?: GamesNumberFormatConfiguration
      sortRank?:
        type: integer
        format: int32
        description: The sort rank of this leaderboard. Writes to this field are ignored.
      name?: LocalizedStringBundle
      iconUrl?:
        type: string
        description: The icon url of this leaderboard. Writes to this field are ignored.
    description: This is a JSON template for a leaderboard configuration detail.
  LeaderboardConfigurationListResponse:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#leaderboardConfigurationListResponse
        description: Uniquely identifies the type of this resource. Value is always the fixed string games#leaderboardConfigurationListResponse.
      nextPageToken?:
        type: string
        description: The pagination token for the next page of results.
      items?:
        type: array
        description: The leaderboard configurations.
        items: LeaderboardConfiguration
    description: This is a JSON template for a ListConfigurations response.
  LocalizedString:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#localizedString
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#localizedString.
      locale?:
        type: string
        description: The locale string.
      value?:
        type: string
        description: The string value.
    description: This is a JSON template for a localized string resource.
  LocalizedStringBundle:
    type: object
    properties:
      kind?:
        type: string
        default: gamesConfiguration#localizedStringBundle
        description: Uniquely identifies the type of this resource. Value is always the fixed string gamesConfiguration#localizedStringBundle.
      translations?:
        type: array
        description: The locale strings.
        items: LocalizedString
    description: This is a JSON template for a localized string bundle resource.
/achievements:
  /{achievementId}:
    uriParameters:
      achievementId:
        type: string
        description: The ID of the achievement used by this method.
    patch:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Update the metadata of the achievement configuration with the given ID. This method supports patch semantics.
      displayName: patch
      is:
      - hasParameters
      body:
        application/json: AchievementConfiguration
      responses:
        200:
          body:
            application/json: AchievementConfiguration
      (commons.Id): gamesConfiguration.achievementConfigurations.patch
      (commons.LogicalStucture):
      - Achievement Configurations
    get:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Retrieves the metadata of the achievement configuration with the given ID.
      displayName: get
      is:
      - hasParameters
      responses:
        200:
          body:
            application/json: AchievementConfiguration
      (commons.Id): gamesConfiguration.achievementConfigurations.get
      (commons.LogicalStucture):
      - Achievement Configurations
    put:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Update the metadata of the achievement configuration with the given ID.
      displayName: update
      is:
      - hasParameters
      body:
        application/json: AchievementConfiguration
      responses:
        200:
          body:
            application/json: AchievementConfiguration
      (commons.Id): gamesConfiguration.achievementConfigurations.update
      (commons.LogicalStucture):
      - Achievement Configurations
    delete:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Delete the achievement configuration with the given ID.
      displayName: delete
      is:
      - hasParameters
      (commons.Id): gamesConfiguration.achievementConfigurations.delete
      (commons.LogicalStucture):
      - Achievement Configurations
/applications:
  /{applicationId}:
    uriParameters:
      applicationId:
        type: string
        description: The application ID from the Google Play developer console.
    /achievements:
      post:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/androidpublisher
        description: Insert a new achievement configuration in this application.
        displayName: insert
        is:
        - hasParameters
        body:
          application/json: AchievementConfiguration
        responses:
          200:
            body:
              application/json: AchievementConfiguration
        (commons.Id): gamesConfiguration.achievementConfigurations.insert
        (commons.LogicalStucture):
        - Achievement Configurations
      get:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/androidpublisher
        description: Returns a list of the achievement configurations in this application.
        displayName: list
        is:
        - hasParameters
        queryParameters:
          maxResults?:
            type: integer
            format: int32
            description: The maximum number of resource configurations to return in the response, used for paging. For any response, the actual number of resources returned may be less than the specified maxResults.
            maximum: 200
            minimum: 1
          pageToken?:
            type: string
            description: The token returned by the previous request.
        responses:
          200:
            body:
              application/json: AchievementConfigurationListResponse
        (commons.Id): gamesConfiguration.achievementConfigurations.list
        (commons.LogicalStucture):
        - Achievement Configurations
    /leaderboards:
      post:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/androidpublisher
        description: Insert a new leaderboard configuration in this application.
        displayName: insert
        is:
        - hasParameters
        body:
          application/json: LeaderboardConfiguration
        responses:
          200:
            body:
              application/json: LeaderboardConfiguration
        (commons.Id): gamesConfiguration.leaderboardConfigurations.insert
        (commons.LogicalStucture):
        - Leaderboard Configurations
      get:
        securedBy:
          oath2:
            scopes:
            - https://www.googleapis.com/auth/androidpublisher
        description: Returns a list of the leaderboard configurations in this application.
        displayName: list
        is:
        - hasParameters
        queryParameters:
          maxResults?:
            type: integer
            format: int32
            description: The maximum number of resource configurations to return in the response, used for paging. For any response, the actual number of resources returned may be less than the specified maxResults.
            maximum: 200
            minimum: 1
          pageToken?:
            type: string
            description: The token returned by the previous request.
        responses:
          200:
            body:
              application/json: LeaderboardConfigurationListResponse
        (commons.Id): gamesConfiguration.leaderboardConfigurations.list
        (commons.LogicalStucture):
        - Leaderboard Configurations
/images:
  /{resourceId}:
    uriParameters:
      resourceId:
        type: string
        description: The ID of the resource used by this method.
    /imageType:
      /{imageType}:
        uriParameters:
          imageType:
            type: string
            description: Selects which image in a resource for this method.
            (commons.EnumDescriptions):
            - The icon image for an achievement resource.
            - The icon image for a leaderboard resource.
            enum:
            - ACHIEVEMENT_ICON
            - LEADERBOARD_ICON
        post:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/androidpublisher
          description: Uploads an image for a resource with the given ID and image type.
          displayName: upload
          is:
          - hasParameters
          responses:
            200:
              body:
                application/json: ImageConfiguration
          (commons.Id): gamesConfiguration.imageConfigurations.upload
          (commons.LogicalStucture):
          - Image Configurations
/leaderboards:
  /{leaderboardId}:
    uriParameters:
      leaderboardId:
        type: string
        description: The ID of the leaderboard.
    patch:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Update the metadata of the leaderboard configuration with the given ID. This method supports patch semantics.
      displayName: patch
      is:
      - hasParameters
      body:
        application/json: LeaderboardConfiguration
      responses:
        200:
          body:
            application/json: LeaderboardConfiguration
      (commons.Id): gamesConfiguration.leaderboardConfigurations.patch
      (commons.LogicalStucture):
      - Leaderboard Configurations
    get:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Retrieves the metadata of the leaderboard configuration with the given ID.
      displayName: get
      is:
      - hasParameters
      responses:
        200:
          body:
            application/json: LeaderboardConfiguration
      (commons.Id): gamesConfiguration.leaderboardConfigurations.get
      (commons.LogicalStucture):
      - Leaderboard Configurations
    put:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Update the metadata of the leaderboard configuration with the given ID.
      displayName: update
      is:
      - hasParameters
      body:
        application/json: LeaderboardConfiguration
      responses:
        200:
          body:
            application/json: LeaderboardConfiguration
      (commons.Id): gamesConfiguration.leaderboardConfigurations.update
      (commons.LogicalStucture):
      - Leaderboard Configurations
    delete:
      securedBy:
        oath2:
          scopes:
          - https://www.googleapis.com/auth/androidpublisher
      description: Delete the leaderboard configuration with the given ID.
      displayName: delete
      is:
      - hasParameters
      (commons.Id): gamesConfiguration.leaderboardConfigurations.delete
      (commons.LogicalStucture):
      - Leaderboard Configurations
