#%RAML 1.0
title: Google Play Movies Partner API
version: v1
baseUri: https://playmoviespartner.googleapis.com/
uses:
  commons: https://raw.githubusercontent.com/apiregistry/commons/master/commons.raml
(commons.Links):
- title: Developer Documentation
  url: https://developers.google.com/playmoviespartner/
  role: documentation
(commons.Icons):
- url: http://www.google.com/images/icons/product/search-32.gif
  name: x32
- url: http://www.google.com/images/icons/product/search-16.gif
  name: x16
(commons.Id): playmoviespartner:v1
securitySchemes:
  oath2:
    type: OAuth 2.0
    description: Google Oath2.0 authorization. Detailed documentation can be found at https://developers.google.com/identity/protocols/OAuth2
    settings:
      authorizationGrants:
      - authorization_code
      - implicit
      authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      accessTokenUri: https://accounts.google.com/o/oauth2/v2/auth
      scopes:
      - https://www.googleapis.com/auth/playmovies_partner.readonly
traits:
  hasParameters:
    queryParameters:
      pp?:
        type: boolean
        default: true
        description: Pretty-print response.
      quotaUser?:
        type: string
        description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      prettyPrint?:
        type: boolean
        default: true
        description: Returns response with indentations and line breaks.
      upload_protocol?:
        type: string
        description: Upload protocol for media (e.g. "raw", "multipart").
      $.xgafv?:
        type: string
        description: V1 error format.
        (commons.EnumDescriptions):
        - v1 error format
        - v2 error format
      uploadType?:
        type: string
        description: Legacy upload protocol for media (e.g. "media", "multipart").
      callback?:
        type: string
        description: JSONP
      fields?:
        type: string
        description: Selector specifying which fields to include in a partial response.
securedBy:
  oath2: 
types:
  Avail:
    type: object
    properties:
      episodeTitleInternalAlias?:
        type: string
        description: 'OPTIONAL.TV Only. Title used by involved parties to refer to
          this episode. Only available on TV Avails. Example: "Coding at Google".'
      displayName?:
        type: string
        description: 'The name of the studio that owns the Edit referred in the Avail.
          This is the equivalent of `studio_name` in other resources, but it follows
          the EMA nomenclature. Example: "Google Films".'
      contentId?:
        type: string
        description: 'Title Identifier. This should be the Title Level EIDR. Example:
          "10.5240/1489-49A2-3956-4B2D-FE16-5".'
      seriesTitleInternalAlias?:
        type: string
        description: 'Title used by involved parties to refer to this series. Only
          available on TV Avails. Example: "Googlers, The".'
      seriesAltId?:
        type: string
        description: 'Other identifier referring to the series, as defined by partner.
          Only available on TV avails. Example: "rs_googlers".'
      availId?:
        type: string
        description: ID internally generated by Google to uniquely identify an Avail. Not part of EMA Specs.
      videoId?:
        type: string
        description: 'Google-generated ID identifying the video linked to this Avail,
          once delivered. Not part of EMA Specs. Example: ''gtry456_xc'''
      seasonTitleInternalAlias?:
        type: string
        description: 'Title used by involved parties to refer to this season. Only
          available on TV Avails. Example: "Googlers, The".'
      episodeNumber?:
        type: string
        description: 'The number assigned to the episode within a season. Only available
          on TV Avails. Example: "3".'
      licenseType?:
        type: string
        description: Type of transaction.
        enum:
        - LICENSE_TYPE_UNSPECIFIED
        - EST
        - VOD
        - SVOD
        - POEST
      end?:
        type: string
        description: 'End of term in YYYY-MM-DD format in the timezone of the country
          of the Avail. "Open" if no end date is available. Example: "2019-02-17"'
      episodeAltId?:
        type: string
        description: 'Other identifier referring to the episode, as defined by partner.
          Only available on TV avails. Example: "rs_googlers_s1_3".'
      seasonAltId?:
        type: string
        description: 'Other identifier referring to the season, as defined by partner.
          Only available on TV avails. Example: "rs_googlers_s1".'
      titleInternalAlias?:
        type: string
        description: 'Title used by involved parties to refer to this content. Example:
          "Googlers, The". Only available on Movie Avails.'
      productId?:
        type: string
        description: 'Edit Identifier. This should be the Edit Level EIDR. Example:
          "10.2340/1489-49A2-3956-4B2D-FE16-6"'
      releaseDate?:
        type: string
        description: 'Release date of the Title in earliest released territory. Typically
          it is just the year, but it is free-form as per EMA spec. Examples: "1979",
          "Oct 2014"'
      formatProfile?:
        type: string
        description: Indicates the format profile covered by the transaction.
        enum:
        - FORMAT_PROFILE_UNSPECIFIED
        - SD
        - HD
      start?:
        type: string
        description: 'Start of term in YYYY-MM-DD format in the timezone of the country
          of the Avail. Example: "2013-05-14".'
      priceType?:
        type: string
        description: 'Type of pricing that should be applied to this Avail based on
          how the partner classify them. Example: "Tier", "WSP", "SRP", or "Category".'
      ratingReason?:
        type: string
        description: 'Value representing the rating reason. Rating reasons should
          be formatted as per [EMA ratings spec](http://www.movielabs.com/md/ratings/)
          and comma-separated for inclusion of multiple reasons. Example: "L, S, V"'
      priceValue?:
        type: string
        description: 'Value to be applied to the pricing type. Example: "4" or "2.99"'
      seasonNumber?:
        type: string
        description: 'The number assigned to the season within a series. Only available
          on TV Avails. Example: "1".'
      ratingSystem?:
        type: string
        description: 'Rating system applied to the version of title within territory
          of Avail. Rating systems should be formatted as per [EMA ratings spec](http://www.movielabs.com/md/ratings/)
          Example: "MPAA"'
      altId?:
        type: string
        description: 'Other identifier referring to the Edit, as defined by partner.
          Example: "GOOGLER_2006"'
      encodeId?:
        type: string
        description: 'Manifestation Identifier. This should be the Manifestation Level
          EIDR. Example: "10.2340/1489-49A2-3956-4B2D-FE16-7"'
      pphNames?:
        type: array
        description: Name of the post-production houses that manage the Avail. Not part of EMA Specs.
        items:
          type: string
      suppressionLiftDate?:
        type: string
        description: 'First date an Edit could be publically announced as becoming
          available at a specific future date in territory of Avail. *Not* the Avail
          start date or pre-order start date. Format is YYYY-MM-DD. Only available
          for pre-orders. Example: "2012-12-10"'
      ratingValue?:
        type: string
        description: 'Value representing the rating. Ratings should be formatted as
          per http://www.movielabs.com/md/ratings/ Example: "PG"'
      workType?:
        type: string
        description: Work type as enumerated in EMA.
        enum:
        - TITLE_TYPE_UNSPECIFIED
        - MOVIE
        - SEASON
        - EPISODE
        - BUNDLE
      storeLanguage?:
        type: string
        description: 'Spoken language of the intended audience. Language shall be
          encoded in accordance with RFC 5646. Example: "fr".'
      captionExemption?:
        type: string
        description: 'Communicating an exempt category as defined by FCC regulations.
          It is not required for non-US Avails. Example: "1"'
      territory?:
        type: string
        description: 'ISO 3166-1 alpha-2 country code for the country or territory
          of this Avail. For Avails, we use Territory in lieu of Country to comply
          with EMA specifications. But please note that Territory and Country identify
          the same thing. Example: "US".'
      captionIncluded?:
        type: boolean
        description: Communicating if caption file will be delivered.
    description: An Avail describes the Availability Window of a specific Edit in a given country, which means the period Google is allowed to sell or rent the Edit. Avails are exposed in EMA format Version 1.6b (available at http://www.movielabs.com/md/avails/) Studios can see the Avails for the Titles they own. Post-production houses cannot see any Avails.
  Component:
    type: object
    properties:
      normalizedPriority?:
        type: string
        description: A simpler representation of the priority.
        enum:
        - NORMALIZED_PRIORITY_UNSPECIFIED
        - LOW_PRIORITY
        - HIGH_PRIORITY
      componentId?:
        type: string
        description: 'ID internally generated by Google to uniquely identify the Component.
          Example: ''wteyrc_647xc'''
      editLevelEidrs?:
        type: array
        description: 'List of Edit-level EIDR IDs. Example: "10.5240/1489-49A2-3956-4B2D-FE16-6".'
        items:
          type: string
      altCutIds?:
        type: array
        description: 'List of Alternative Cut IDs, sometimes available in lieu of
          the main Edit-level EIDR IDs. This is not an EIDR ID, but a Partner-provided
          ID. Example: "206346_79838".'
        items:
          type: string
      pphName?:
        type: string
        description: Name of the post-production house that manages the Component.
      processingErrors?:
        type: array
        description: 'Processing errors during XML file parsing. Example: ''Invalid
          input file'''
        items:
          type: string
      componentDetailType?:
        type: string
        description: Detail about the type of the Component.
        enum:
        - COMPONENT_DETAIL_TYPE_UNSPECIFIED
        - COMPONENT_DETAIL_TYPE_NORMAL
        - COMPONENT_DETAIL_TYPE_POSTER
        - COMPONENT_DETAIL_TYPE_PRIMARY
        - COMPONENT_DETAIL_TYPE_FORCED
        - COMPONENT_DETAIL_TYPE_DUBBED
        - COMPONENT_DETAIL_TYPE_SDH
      studioName?:
        type: string
        description: Name of the studio that owns the Component.
      customIds?:
        type: array
        description: 'List of custom IDs (defined by the partner) linked to the ExperienceLocale
          using this Component. Example: "R86241"'
        items:
          type: string
      language?:
        type: string
        description: 'Language of the component, using the "BCP 47" format. Examples:
          "en", "en-US", "es", "es-419".'
      statusDetail?:
        type: string
        description: Detailed status of the Component
        enum:
        - COMPONENT_STATUS_UNSPECIFIED
        - COMPONENT_STATUS_QC_APPROVED
        - COMPONENT_STATUS_QC_REJECTION
        - COMPONENT_STATUS_FILE_REJECTION
        - COMPONENT_STATUS_FILE_PROCESSING
        - COMPONENT_STATUS_READY_FOR_QC
      type?:
        type: string
        description: 'Type of the Component. Example: AUDIO_51'
        enum:
        - COMPONENT_TYPE_UNSPECIFIED
        - VIDEO
        - AUDIO_20
        - AUDIO_51
        - SUBTITLE
        - ARTWORK
        - METADATA
      priority?:
        type: number
        format: double
        description: Component priority, as defined by Google. The higher the value, the higher the priority.
      elIds?:
        type: array
        description: 'IDs internally generated by Google to uniquely identify the
          ExperienceLocales for which the Component is used. Example: ''KRZiVjY9h7t'''
        items:
          type: string
      titleLevelEidrs?:
        type: array
        description: 'List of Title-level EIDR IDs. Example: "10.5240/1489-49A2-3956-4B2D-FE16-5".'
        items:
          type: string
      filename?:
        type: string
        description: File name of the Component when delivered.
      playableUnitType?:
        type: string
        description: Type of the playable unit for which the Component is intended.
        enum:
        - PLAYABLE_UNIT_TYPE_UNSPECIFIED
        - PLAYABLE_UNIT_TYPE_FEATURE
        - PLAYABLE_UNIT_TYPE_TRAILER
        - PLAYBLE_UNIT_TYPE_BONUS_CONTENT
      receivedTime?:
        type: string
        description: Timestamp when the Component was received.
      approvedTime?:
        type: string
        description: Timestamp when the Component was approved.
      name?:
        type: string
        description: 'Default Edit name, usually in the language of the country of
          origin. Example: "Googlers, The".'
      rejectionNote?:
        type: string
        description: Notes explaining why a Component has been rejected.
      status?:
        type: string
        description: High-level status of the Component.
        enum:
        - STATUS_UNSPECIFIED
        - STATUS_APPROVED
        - STATUS_FAILED
        - STATUS_PROCESSING
        - STATUS_UNFULFILLED
        - STATUS_NOT_AVAILABLE
    description: A Component is an element (audio, video, subtitle, artwork, trailer, etc...) that is used in a set of ExperienceLocales. A Component is owned by a Studio and managed either by the Studio itself or by one Post-Production House. Each Component is identified by a `component_id` and its `type`.
  ExperienceLocale:
    type: object
    properties:
      country?:
        type: string
        description: 'Country where the ExperienceLocale is available, using the "ISO
          3166-1 alpha-2" format. Example: "US".'
      normalizedPriority?:
        type: string
        description: A simpler representation of the priority.
        enum:
        - NORMALIZED_PRIORITY_UNSPECIFIED
        - LOW_PRIORITY
        - HIGH_PRIORITY
      studioName?:
        type: string
        description: Name of the studio that owns the ExperienceLocale.
      customIds?:
        type: array
        description: 'List of custom IDs (defined by the partner) linked to this ExperienceLocale.
          Example: "R86241"'
        items:
          type: string
      language?:
        type: string
        description: 'Language of the ExperienceLocale, using the "BCP 47" format.
          Examples: "en", "en-US", "es", "es-419".'
      videoId?:
        type: string
        description: 'Video ID, as defined by Google, linked to the feature video
          in the ExperienceLocale. Example: ''gtry456_xc''.'
      type?:
        type: string
        description: Type of the Edit linked to the ExperienceLocale.
        enum:
        - TITLE_TYPE_UNSPECIFIED
        - MOVIE
        - SEASON
        - EPISODE
        - BUNDLE
      priority?:
        type: number
        format: double
        description: 'ExperienceLocale priority, as defined by Google. The higher
          the value, the higher the priority. Example: 90'
      elId?:
        type: string
        description: 'ID internally generated by Google to uniquely identify a ExperienceLocale.
          Example: ''KRZiVjY9h7t'''
      pphNames?:
        type: array
        description: Name of the post-production houses that manage the ExperienceLocale.
        items:
          type: string
      editLevelEidr?:
        type: string
        description: 'Edit-level EIDR ID. Example: "10.5240/1489-49A2-3956-4B2D-FE16-6".'
      presentationId?:
        type: string
        description: PresentationID as defined in the EMA specs.
      playableSequenceId?:
        type: string
        description: PlayableSequenceID as defined in the EMA specs.
      altCutId?:
        type: string
        description: 'Alternative Cut ID, sometimes available in lieu of the main
          Edit-level EIDR ID. This is not an EIDR ID, but a Partner-provided ID. Example:
          "206346_79838".'
      inventoryId?:
        type: string
        description: InventoryID as defined in the EMA specs.
      name?:
        type: string
        description: 'Default Edit name, usually in the language of the country of
          origin. Example: "Googlers, The".'
      approvedTime?:
        type: string
        description: Timestamp when the ExperienceLocale was approved.
      createdTime?:
        type: string
        description: Timestamp when the ExperienceLocale was created.
      titleLevelEidr?:
        type: string
        description: 'Title-level EIDR ID. Example: "10.5240/1489-49A2-3956-4B2D-FE16-5".'
      trailerId?:
        type: string
        description: 'Trailer ID, as defined by Google, linked to the trailer video
          in the ExperienceLocale. Example: ''gtry457_tr''.'
      earliestAvailStartTime?:
        type: string
        description: Timestamp of the earliest start date of the Avails linked to this ExperienceLocale.
      channelId?:
        type: string
        description: 'YouTube Channel ID linked to the ExperienceLocale. Example:
          "UCRG64darCZhb".'
      status?:
        type: string
        description: High-level status of the ExperienceLocale.
        enum:
        - STATUS_UNSPECIFIED
        - STATUS_APPROVED
        - STATUS_FAILED
        - STATUS_PROCESSING
        - STATUS_UNFULFILLED
        - STATUS_NOT_AVAILABLE
    description: 'An ExperienceLocale tracks the fulfillment of a Title in a country
      using a specific language, when delivered using component-based delivery. For
      example, a Title in Switzerland might have 3 ExperienceLocales: they both share
      the same country ("CH"), but each has different languages ("de", "fr", and "it").
      Each ExperienceLocale is uniquely identified by an `el_id`, which is generated
      by Google. Externally, an ExperienceLocale can also be identified by partners
      using its EIDR IDs, AltCutID or `custom_id` (when provided).'
  ListAvailsResponse:
    type: object
    properties:
      totalSize?:
        type: integer
        format: int32
        description: See _List methods rules_ for more information about this field.
      avails?:
        type: array
        description: List of Avails that match the request criteria.
        items: Avail
      nextPageToken?:
        type: string
        description: See _List methods rules_ for info about this field.
    description: Response to the 'ListAvails' method.
  ListComponentsResponse:
    type: object
    properties:
      components?:
        type: array
        description: List of Components that match the request criteria.
        items: Component
      totalSize?:
        type: integer
        format: int32
        description: See _List methods rules_ for more information about this field.
      nextPageToken?:
        type: string
        description: See _List methods rules_ for info about this field.
    description: Response to the 'ListComponents' method.
  ListExperienceLocalesResponse:
    type: object
    properties:
      totalSize?:
        type: integer
        format: int32
        description: See _List methods rules_ for more information about this field.
      nextPageToken?:
        type: string
        description: See _List methods rules_ for info about this field.
      experienceLocales?:
        type: array
        description: List of ExperienceLocales that match the request criteria.
        items: ExperienceLocale
    description: Response to the 'ListExperienceLocales' method.
  ListOrdersResponse:
    type: object
    properties:
      totalSize?:
        type: integer
        format: int32
        description: See _List methods rules_ for more information about this field.
      nextPageToken?:
        type: string
        description: See _List methods rules_ for info about this field.
      orders?:
        type: array
        description: List of Orders that match the request criteria.
        items: Order
    description: Response to the 'ListOrders' method.
  ListStoreInfosResponse:
    type: object
    properties:
      totalSize?:
        type: integer
        format: int32
        description: See _List methods rules_ for more information about this field.
      nextPageToken?:
        type: string
        description: See 'List methods rules' for info about this field.
      storeInfos?:
        type: array
        description: List of StoreInfos that match the request criteria.
        items: StoreInfo
    description: Response to the 'ListStoreInfos' method.
  Order:
    type: object
    properties:
      orderedTime?:
        type: string
        description: Timestamp when the Order was created.
      normalizedPriority?:
        type: string
        description: A simpler representation of the priority.
        enum:
        - NORMALIZED_PRIORITY_UNSPECIFIED
        - LOW_PRIORITY
        - HIGH_PRIORITY
      showName?:
        type: string
        description: 'Default Show name, usually in the language of the country of
          origin. Only available for TV Edits Example: "Googlers, The".'
      pphName?:
        type: string
        description: Name of the post-production house that manages the Edit ordered.
      orderId?:
        type: string
        description: 'ID internally generated by Google to uniquely identify an Order.
          Example: ''abcde12_x'''
      episodeName?:
        type: string
        description: 'Default Episode name, usually in the language of the country
          of origin. Only available for TV Edits Example: "Googlers, The - Pilot".'
      studioName?:
        type: string
        description: Name of the studio that owns the Edit ordered.
      legacyPriority?:
        type: string
        description: 'Legacy Order priority, as defined by Google. Example: ''P0'''
      videoId?:
        type: string
        description: 'Google-generated ID identifying the video linked to this Order,
          once delivered. Example: ''gtry456_xc''.'
      statusDetail?:
        type: string
        description: Detailed status of the order
        enum:
        - ORDER_STATUS_UNSPECIFIED
        - ORDER_STATUS_QC_APPROVED
        - ORDER_STATUS_QC_REJECTION
        - ORDER_STATUS_INTERNAL_FIX
        - ORDER_STATUS_OPEN_ORDER
        - ORDER_STATUS_NOT_AVAILABLE
        - ORDER_STATUS_AWAITING_REDELIVERY
        - ORDER_STATUS_READY_FOR_QC
        - ORDER_STATUS_FILE_PROCESSING
      countries?:
        type: array
        description: 'Countries where the Order is available, using the "ISO 3166-1
          alpha-2" format (example: "US").'
        items:
          type: string
      type?:
        type: string
        description: Type of the Edit linked to the Order.
        enum:
        - TITLE_TYPE_UNSPECIFIED
        - MOVIE
        - SEASON
        - EPISODE
        - BUNDLE
      priority?:
        type: number
        format: double
        description: 'Order priority, as defined by Google. The higher the value,
          the higher the priority. Example: 90'
      customId?:
        type: string
        description: 'ID that can be used to externally identify an Order. This ID
          is provided by partners when submitting the Avails. Example: ''GOOGLER_2006'''
      seasonName?:
        type: string
        description: 'Default Season name, usually in the language of the country
          of origin. Only available for TV Edits Example: "Googlers, The - A Brave
          New World".'
      receivedTime?:
        type: string
        description: Timestamp when the Order was fulfilled.
      name?:
        type: string
        description: 'Default Edit name, usually in the language of the country of
          origin. Example: "Googlers, The".'
      approvedTime?:
        type: string
        description: Timestamp when the Order was approved.
      channelName?:
        type: string
        description: 'YouTube Channel Name that should be used to fulfill the Order.
          Example: "Google_channel".'
      rejectionNote?:
        type: string
        description: 'Field explaining why an Order has been rejected. Example: "Trailer
          audio is 2ch mono, please re-deliver in stereo".'
      earliestAvailStartTime?:
        type: string
        description: Timestamp of the earliest start date of the Avails linked to this Order.
      channelId?:
        type: string
        description: 'YouTube Channel ID that should be used to fulfill the Order.
          Example: "UCRG64darCZhb".'
      status?:
        type: string
        description: High-level status of the order.
        enum:
        - STATUS_UNSPECIFIED
        - STATUS_APPROVED
        - STATUS_FAILED
        - STATUS_PROCESSING
        - STATUS_UNFULFILLED
        - STATUS_NOT_AVAILABLE
    description: An Order tracks the fulfillment of an Edit when delivered using the legacy, non-component-based delivery. Each Order is uniquely identified by an `order_id`, which is generated by Google. Externally, Orders can also be identified by partners using its `custom_id` (when provided).
  StoreInfo:
    type: object
    properties:
      country?:
        type: string
        description: 'Country where Edit is available in ISO 3166-1 alpha-2 country
          code. Example: "US".'
      hasAudio51?:
        type: boolean
        description: Whether the Edit has a 5.1 channel audio track.
      hasInfoCards?:
        type: boolean
        description: Whether the Edit has info cards.
      studioName?:
        type: string
        description: Name of the studio that owns the Edit ordered.
      mid?:
        type: string
        description: 'Knowledge Graph ID associated to this Edit, if available. This
          ID links the Edit to its knowledge entity, externally accessible at http://freebase.com.
          In the absense of Title EIDR or Edit EIDR, this ID helps link together multiple
          Edits across countries. Example: ''/m/0ffx29'''
      videoId?:
        type: string
        description: 'Google-generated ID identifying the video linked to the Edit.
          Example: ''gtry456_xc'''
      type?:
        type: string
        description: Edit type, like Movie, Episode or Season.
        enum:
        - TITLE_TYPE_UNSPECIFIED
        - MOVIE
        - SEASON
        - EPISODE
        - BUNDLE
      episodeNumber?:
        type: string
        description: 'The number assigned to the episode within a season. Only available
          on TV Edits. Example: "1".'
      audioTracks?:
        type: array
        description: Audio tracks available for this Edit.
        items:
          type: string
      showId?:
        type: string
        description: 'Google-generated ID identifying the show linked to the Edit.
          Only available for TV Edits. Example: ''et2hsue_x'''
      seasonId?:
        type: string
        description: 'Google-generated ID identifying the season linked to the Edit.
          Only available for TV Edits. Example: ''ster23ex'''
      seasonName?:
        type: string
        description: 'Default Season name, usually in the language of the country
          of origin. Only available for TV Edits Example: "Googlers, The - A Brave
          New World".'
      liveTime?:
        type: string
        description: Timestamp when the Edit went live on the Store.
      hasHdOffer?:
        type: boolean
        description: Whether the Edit has a HD offer.
      subtitles?:
        type: array
        description: Subtitles available for this Edit.
        items:
          type: string
      showName?:
        type: string
        description: 'Default Show name, usually in the language of the country of
          origin. Only available for TV Edits Example: "Googlers, The".'
      hasEstOffer?:
        type: boolean
        description: Whether the Edit has a EST offer.
      seasonNumber?:
        type: string
        description: 'The number assigned to the season within a show. Only available
          on TV Edits. Example: "1".'
      hasVodOffer?:
        type: boolean
        description: Whether the Edit has a VOD offer.
      pphNames?:
        type: array
        description: Name of the post-production houses that manage the Edit.
        items:
          type: string
      hasSdOffer?:
        type: boolean
        description: Whether the Edit has a SD offer.
      editLevelEidr?:
        type: string
        description: 'Edit-level EIDR ID. Example: "10.5240/1489-49A2-3956-4B2D-FE16-6".'
      name?:
        type: string
        description: 'Default Edit name, usually in the language of the country of
          origin. Example: "Googlers, The".'
      titleLevelEidr?:
        type: string
        description: 'Title-level EIDR ID. Example: "10.5240/1489-49A2-3956-4B2D-FE16-5".'
      trailerId?:
        type: string
        description: 'Google-generated ID identifying the trailer linked to the Edit.
          Example: ''bhd_4e_cx'''
    description: Information about a playable sequence (video) associated with an Edit and available at the Google Play Store. Internally, each StoreInfo is uniquely identified by a `video_id` and `country`. Externally, Title-level EIDR or Edit-level EIDR, if provided, can also be used to identify a specific title or edit in a country.
/v1:
  /accounts:
    /{accountId}:
      uriParameters:
        accountId:
          type: string
          description: REQUIRED. See _General rules_ for more information about this field.
      /components:
        /{componentId}:
          uriParameters:
            componentId:
              type: string
              description: REQUIRED. Component ID.
          /type:
            /{type}:
              uriParameters:
                type:
                  type: string
                  description: REQUIRED. Component Type.
                  enum:
                  - COMPONENT_TYPE_UNSPECIFIED
                  - VIDEO
                  - AUDIO_20
                  - AUDIO_51
                  - SUBTITLE
                  - ARTWORK
                  - METADATA
              get:
                securedBy:
                  oath2:
                    scopes:
                    - https://www.googleapis.com/auth/playmovies_partner.readonly
                description: Get a Component given its id.
                displayName: Get
                is:
                - hasParameters
                responses:
                  200:
                    body:
                      application/json: Component
                (commons.Id): playmoviespartner.accounts.components.type.get
                (commons.LogicalStructure):
                - Accounts
                - Components
                - Type
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/playmovies_partner.readonly
          description: List Components owned or managed by the partner. See _Authentication and Authorization rules_ and _List methods rules_ for more information about this method.
          displayName: List
          is:
          - hasParameters
          queryParameters:
            studioNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            pageSize?:
              type: integer
              format: int32
              description: See _List methods rules_ for info about this field.
            customId?:
              type: string
              description: Filter Components that match a case-insensitive partner-specific custom id.
            elId?:
              type: string
              description: Experience ID, as defined by Google.
            pphNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            editLevelEidr?:
              type: string
              description: Filter Components that match a given edit-level EIDR.
            presentationId?:
              type: string
              description: PresentationID available in Common Manifest.
            playableSequenceId?:
              type: string
              description: PlayableSequenceID available in Common Manifest.
            filename?:
              type: string
              description: Filter Components that match a case-insensitive substring of the physical name of the delivered file.
            inventoryId?:
              type: string
              description: InventoryID available in Common Manifest.
            altCutId?:
              type: string
              description: Filter Components that match a case-insensitive, partner-specific Alternative Cut ID.
            titleLevelEidr?:
              type: string
              description: Filter Components that match a given title-level EIDR.
            pageToken?:
              type: string
              description: See _List methods rules_ for info about this field.
            status?:
              type: string
              description: Filter Components that match one of the given status.
              enum:
              - STATUS_UNSPECIFIED
              - STATUS_APPROVED
              - STATUS_FAILED
              - STATUS_PROCESSING
              - STATUS_UNFULFILLED
              - STATUS_NOT_AVAILABLE
          responses:
            200:
              body:
                application/json: ListComponentsResponse
          (commons.Id): playmoviespartner.accounts.components.list
          (commons.LogicalStructure):
          - Accounts
          - Components
      /avails:
        /{availId}:
          uriParameters:
            availId:
              type: string
              description: REQUIRED. Avail ID.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/playmovies_partner.readonly
            description: Get an Avail given its avail group id and avail id.
            displayName: Get
            is:
            - hasParameters
            responses:
              200:
                body:
                  application/json: Avail
            (commons.Id): playmoviespartner.accounts.avails.get
            (commons.LogicalStructure):
            - Accounts
            - Avails
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/playmovies_partner.readonly
          description: List Avails owned or managed by the partner. See _Authentication and Authorization rules_ and _List methods rules_ for more information about this method.
          displayName: List
          is:
          - hasParameters
          queryParameters:
            studioNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            altIds?:
              type: string
              description: Filter Avails that match (case-insensitive) any of the given partner-specific custom ids.
            territories?:
              type: string
              description: 'Filter Avails that match (case-insensitive) any of the
                given country codes, using the "ISO 3166-1 alpha-2" format (examples:
                "US", "us", "Us").'
            pageSize?:
              type: integer
              format: int32
              description: See _List methods rules_ for info about this field.
            pageToken?:
              type: string
              description: See _List methods rules_ for info about this field.
            title?:
              type: string
              description: Filter that matches Avails with a `title_internal_alias`, `series_title_internal_alias`, `season_title_internal_alias`, or `episode_title_internal_alias` that contains the given case-insensitive title.
            altId?:
              type: string
              description: 'Filter Avails that match a case-insensitive, partner-specific
                custom id. NOTE: this field is deprecated and will be removed on V2;
                `alt_ids` should be used instead.'
            videoIds?:
              type: string
              description: Filter Avails that match any of the given `video_id`s.
            pphNames?:
              type: string
              description: See _List methods rules_ for info about this field.
          responses:
            200:
              body:
                application/json: ListAvailsResponse
          (commons.Id): playmoviespartner.accounts.avails.list
          (commons.LogicalStructure):
          - Accounts
          - Avails
      /orders:
        /{orderId}:
          uriParameters:
            orderId:
              type: string
              description: REQUIRED. Order ID.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/playmovies_partner.readonly
            description: Get an Order given its id. See _Authentication and Authorization rules_ and _Get methods rules_ for more information about this method.
            displayName: Get
            is:
            - hasParameters
            responses:
              200:
                body:
                  application/json: Order
            (commons.Id): playmoviespartner.accounts.orders.get
            (commons.LogicalStructure):
            - Accounts
            - Orders
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/playmovies_partner.readonly
          description: List Orders owned or managed by the partner. See _Authentication and Authorization rules_ and _List methods rules_ for more information about this method.
          displayName: List
          is:
          - hasParameters
          queryParameters:
            studioNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            name?:
              type: string
              description: Filter that matches Orders with a `name`, `show`, `season` or `episode` that contains the given case-insensitive name.
            pageSize?:
              type: integer
              format: int32
              description: See _List methods rules_ for info about this field.
            pageToken?:
              type: string
              description: See _List methods rules_ for info about this field.
            customId?:
              type: string
              description: Filter Orders that match a case-insensitive, partner-specific custom id.
            videoIds?:
              type: string
              description: Filter Orders that match any of the given `video_id`s.
            pphNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            status?:
              type: string
              description: Filter Orders that match one of the given status.
              enum:
              - STATUS_UNSPECIFIED
              - STATUS_APPROVED
              - STATUS_FAILED
              - STATUS_PROCESSING
              - STATUS_UNFULFILLED
              - STATUS_NOT_AVAILABLE
          responses:
            200:
              body:
                application/json: ListOrdersResponse
          (commons.Id): playmoviespartner.accounts.orders.list
          (commons.LogicalStructure):
          - Accounts
          - Orders
      /experienceLocales:
        /{elId}:
          uriParameters:
            elId:
              type: string
              description: REQUIRED. ExperienceLocale ID, as defined by Google.
          get:
            securedBy:
              oath2:
                scopes:
                - https://www.googleapis.com/auth/playmovies_partner.readonly
            description: Get an ExperienceLocale given its id. See _Authentication and Authorization rules_ and _Get methods rules_ for more information about this method.
            displayName: Get
            is:
            - hasParameters
            responses:
              200:
                body:
                  application/json: ExperienceLocale
            (commons.Id): playmoviespartner.accounts.experienceLocales.get
            (commons.LogicalStructure):
            - Accounts
            - Experience Locales
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/playmovies_partner.readonly
          description: List ExperienceLocales owned or managed by the partner. See _Authentication and Authorization rules_ and _List methods rules_ for more information about this method.
          displayName: List
          is:
          - hasParameters
          queryParameters:
            studioNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            editLevelEidr?:
              type: string
              description: Filter ExperienceLocales that match a given edit-level EIDR.
            altCutId?:
              type: string
              description: Filter ExperienceLocales that match a case-insensitive, partner-specific Alternative Cut ID.
            pageSize?:
              type: integer
              format: int32
              description: See _List methods rules_ for info about this field.
            titleLevelEidr?:
              type: string
              description: Filter ExperienceLocales that match a given title-level EIDR.
            pageToken?:
              type: string
              description: See _List methods rules_ for info about this field.
            customId?:
              type: string
              description: Filter ExperienceLocales that match a case-insensitive, partner-specific custom id.
            pphNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            status?:
              type: string
              description: Filter ExperienceLocales that match one of the given status.
              enum:
              - STATUS_UNSPECIFIED
              - STATUS_APPROVED
              - STATUS_FAILED
              - STATUS_PROCESSING
              - STATUS_UNFULFILLED
              - STATUS_NOT_AVAILABLE
          responses:
            200:
              body:
                application/json: ListExperienceLocalesResponse
          (commons.Id): playmoviespartner.accounts.experienceLocales.list
          (commons.LogicalStructure):
          - Accounts
          - Experience Locales
      /storeInfos:
        /{videoId}:
          uriParameters:
            videoId:
              type: string
              description: REQUIRED. Video ID.
          /country:
            /{country}:
              uriParameters:
                country:
                  type: string
                  description: REQUIRED. Edit country.
              get:
                securedBy:
                  oath2:
                    scopes:
                    - https://www.googleapis.com/auth/playmovies_partner.readonly
                description: Get a StoreInfo given its video id and country. See _Authentication and Authorization rules_ and _Get methods rules_ for more information about this method.
                displayName: Get
                is:
                - hasParameters
                responses:
                  200:
                    body:
                      application/json: StoreInfo
                (commons.Id): playmoviespartner.accounts.storeInfos.country.get
                (commons.LogicalStructure):
                - Accounts
                - Store Infos
                - Country
        get:
          securedBy:
            oath2:
              scopes:
              - https://www.googleapis.com/auth/playmovies_partner.readonly
          description: List StoreInfos owned or managed by the partner. See _Authentication and Authorization rules_ and _List methods rules_ for more information about this method.
          displayName: List
          is:
          - hasParameters
          queryParameters:
            studioNames?:
              type: string
              description: See _List methods rules_ for info about this field.
            name?:
              type: string
              description: Filter that matches StoreInfos with a `name` or `show_name` that contains the given case-insensitive name.
            mids?:
              type: string
              description: Filter StoreInfos that match any of the given `mid`s.
            seasonIds?:
              type: string
              description: Filter StoreInfos that match any of the given `season_id`s.
            pageSize?:
              type: integer
              format: int32
              description: See _List methods rules_ for info about this field.
            videoId?:
              type: string
              description: 'Filter StoreInfos that match a given `video_id`. NOTE:
                this field is deprecated and will be removed on V2; `video_ids` should
                be used instead.'
            pageToken?:
              type: string
              description: See _List methods rules_ for info about this field.
            countries?:
              type: string
              description: 'Filter StoreInfos that match (case-insensitive) any of
                the given country codes, using the "ISO 3166-1 alpha-2" format (examples:
                "US", "us", "Us").'
            videoIds?:
              type: string
              description: Filter StoreInfos that match any of the given `video_id`s.
            pphNames?:
              type: string
              description: See _List methods rules_ for info about this field.
          responses:
            200:
              body:
                application/json: ListStoreInfosResponse
          (commons.Id): playmoviespartner.accounts.storeInfos.list
          (commons.LogicalStructure):
          - Accounts
          - Store Infos
